services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - ./data:/app/data
    expose:
      - "5000"

  web:
    image: nginx:1.25
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
